apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: ${TIDB_NAME}-core-components
  namespace: ${NAMESPACE}
spec:
  namespaceSelector:
    matchNames: ["${NAMESPACE}"]
  selector:
    matchLabels:
      app.kubernetes.io/instance: ${TIDB_NAME}
  podMetricsEndpoints:
    - interval: 15s
      honorLabels: true
      port: status
      path: /metrics
      relabelConfigs:
        - action: keep
          sourceLabels: [__meta_kubernetes_namespace]
          regex: ${NAMESPACE}
        - action: keep
          sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          regex: "true"
        - action: keep
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          regex: pd|tidb|tiflash|tikv
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          targetLabel: job
          replacement: ${TIDB_NAME}-$1
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
            - __meta_kubernetes_pod_label_app_kubernetes_io_component
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          regex: (.+);(.+);(.+);(.+);(.+)
          replacement: $1.$2-$3-peer.$4:$5
          targetLabel: __address__
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: kubernetes_namespace
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
          targetLabel: cluster
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: instance
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          targetLabel: component
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          separator: "-"
          targetLabel: tidb_cluster
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          targetLabel: __metrics_path__
          regex: (.+)
